import os
import json
import shutil
import subprocess
import threading
from pathlib import Path

# Assuming standard SQLAlchemy models based on previous context
# from models import db, Project, Customer

CROSS_MIG_TEMPLATE_DIR = "/opt/erp/templates/cross-mig" # The path to your uploaded cross-mig repo
EXECUTIONS_BASE_DIR = "/opt/erp/executions"

class ExecutionOrchestrator:
    @staticmethod
    def prepare_workspace(project, customer):
        """Creates an isolated execution directory for the project and generates .tfvars"""
        workspace_dir = os.path.join(EXECUTIONS_BASE_DIR, f"proj_{project.id}")
        
        # 1. Create an isolated copy of the cross-mig terraform repo for this specific run
        if not os.path.exists(workspace_dir):
            shutil.copytree(CROSS_MIG_TEMPLATE_DIR, workspace_dir)
            
        # 2. Extract Target Node (Assuming basic 1-1 migration for now)
        target_node = next((n for n in project.mapper_nodes if n.get('type') == 'ECS'), None)
        target_network = next((n for n in project.mapper_nodes if n.get('type') == 'VPC'), None)
        
        if not target_node or not target_network:
            raise ValueError("Blueprint missing required ECS or VPC nodes.")

        # 3. Determine the Active Credentials based on Least-Privilege
        # Fallback to Tier 1/Master if Sandbox (Tier 2) isn't populated
        active_ak = customer.tier2_ak or customer.ak
        active_sk = customer.tier2_sk or customer.sk

        # 4. Map ERP variables directly to main.tf expected inputs
        tfvars = {
            "access_key": active_ak,
            "secret_key": active_sk,
            "domain_name": customer.domain_name or customer.name,
            
            # Enterprise Project Boundaries
            "enterprise_project_id": project.sandbox_eps,
            
            # Regional & Infrastructure Specs
            "source_region": project.source_region or "la-south-2",
            "target_region": project.target_region or "la-south-2",
            "source_server_id": target_node.get('source_id', ''),
            "target_vpc_name": target_network.get('name', 'vpc-migration'),
            "target_vpc_cidr": target_network.get('cidr', '10.0.0.0/16'),
            "target_subnet_cidr": target_network.get('subnet_cidr', '10.0.1.0/24'),
            "target_server_name": target_node.get('name', 'migrated-ecs'),
            "target_image_id": target_node.get('os_image_id', ''),
            "target_flavor_id": target_node.get('flavor', ''),
            "eip_bandwidth_mbps": int(target_node.get('eip_bandwidth', 0)),
        }

        # 5. Handle Data Plane / OS Credentials based on the Strategy Matrix
        if 'Local OS Admin' in project.auth_level or 'Active Directory' in project.auth_level:
            tfvars["rsync_target_user"] = customer.os_user
            tfvars["rsync_target_password"] = customer.os_password
            if customer.os_domain:
                tfvars["rsync_target_user"] = f"{customer.os_domain}\\{customer.os_user}"

        # 6. Write the terraform.tfvars.json file
        tfvars_path = os.path.join(workspace_dir, "terraform.tfvars.json")
        with open(tfvars_path, "w") as f:
            json.dump(tfvars, f, indent=2)
            
        return workspace_dir

    @staticmethod
    def run_terraform_async(workspace_dir, project_id):
        """Runs the Terraform apply locally in a background thread."""
        def worker():
            try:
                print(f"[PROJ {project_id}] Starting Terraform Init...")
                subprocess.run(["terraform", "init"], cwd=workspace_dir, check=True)
                
                print(f"[PROJ {project_id}] Starting Terraform Apply...")
                # Triggers main.tf which triggers run_migration.sh (Python scripts)
                subprocess.run(
                    ["terraform", "apply", "-var-file=terraform.tfvars.json", "-auto-approve"], 
                    cwd=workspace_dir, 
                    check=True
                )
                print(f"[PROJ {project_id}] Terraform Execution Completed Successfully.")
                
                # We do NOT update project status to 'completed' here. 
                # We wait for the Polling Engine to verify migration_result.json
            except subprocess.CalledProcessError as e:
                print(f"[PROJ {project_id}] ❌ Terraform Execution Failed: {e}")

        # Spawn background thread to prevent blocking the Flask API response
        thread = threading.Thread(target=worker)
        thread.start()

    @staticmethod
    def get_live_status(project_id):
        """Reads the task_poll_latest.json generated by cross-mig to feed the UI Progress Bar."""
        workspace_dir = os.path.join(EXECUTIONS_BASE_DIR, f"proj_{project_id}")
        poll_file = os.path.join(workspace_dir, "out", "task_poll_latest.json")
        result_file = os.path.join(workspace_dir, "out", "migration_result.json")

        status_payload = {
            "state": "INITIALIZING",
            "progress_percentage": 0,
            "details": "Preparing Landing Zone..."
        }

        # 1. Check if the final result file exists (Execution Complete)
        if os.path.exists(result_file):
            with open(result_file, "r") as f:
                data = json.load(f)
            status_payload["state"] = "MIGRATE_SUCCESS" if data.get("success") else "FAILED"
            status_payload["progress_percentage"] = 100
            status_payload["details"] = f"Final Target Server: {data.get('target_server_name', 'Unknown')}"
            return status_payload

        # 2. Check the live polling file for in-flight progress
        if os.path.exists(poll_file):
            try:
                with open(poll_file, "r") as f:
                    data = json.load(f)
                    
                raw_state = data.get("state", "RUNNING")
                status_payload["state"] = raw_state
                
                # Calculate percentages from replicatesize / totalsize
                rep = data.get("replicatesize")
                tot = data.get("totalsize")
                
                if rep is not None and tot is not None and tot > 0:
                    status_payload["progress_percentage"] = round((rep / tot) * 100, 1)
                else:
                    status_payload["progress_percentage"] = data.get("progress") or 50 # Fallback
                
                status_payload["details"] = f"Attempt {data.get('attempt', 1)}. Status: {raw_state}"
                
            except json.JSONDecodeError:
                pass # File might be mid-write by the python script

        return status_payload
