#!/bin/bash
# get_missing_info.sh
# Script to get missing Redis/Memcached information

echo "================================================"
echo "GET MISSING REDIS/MEMCACHED INFORMATION"
echo "================================================"

echo ""
echo "🚨 MISSING INFORMATION REQUIRED:"
echo "================================================"
echo ""
echo "Please provide the following from Huawei Cloud Console:"
echo ""
echo "📋 REDIS INSTANCE (dcs-r0il):"
echo "----------------------------------------"
echo "1. Private IP Address: _______________"
echo "2. Specification (e.g., redis.ha.xu1.large.4): _______________"
echo "3. Capacity (GB): _______________"
echo "4. Engine Version (e.g., Redis 5.0): _______________"
echo "5. Architecture (Single/HA/Cluster/Proxy): _______________"
echo "6. Password Enabled: Yes/No"
echo "7. If Yes, Password: _______________"
echo "8. SSL Enabled: Yes/No"
echo ""
echo "📋 MEMCACHED INSTANCE (dcs-ibu2):"
echo "----------------------------------------"
echo "1. Private IP Address: _______________"
echo "2. Specification (e.g., memcached.ha.xu1.large.8): _______________"
echo "3. Capacity (GB): _______________"
echo "4. Architecture (Single/HA): _______________"
echo "5. Password Enabled: Yes/No"
echo "6. If Yes, Password: _______________"
echo ""
echo "🔧 HOW TO GET THIS INFORMATION:"
echo "================================================"
echo ""
echo "Step 1: Login to Huawei Cloud Console"
echo "   URL: https://console.huaweicloud.com/dcs"
echo ""
echo "Step 2: Select correct project and region"
echo "   Project: 08720a7af300f48a2f48c00622277d5d"
echo "   Region: af-south-1 (AF-Johannesburg)"
echo ""
echo "Step 3: For Redis (dcs-r0il):"
echo "   1. Click 'Redis' tab"
echo "   2. Find instance 'dcs-r0il'"
echo "   3. Click on instance name"
echo "   4. In 'Basic Information' section, find:"
echo "      - Private IP"
echo "      - Specification"
echo "      - Capacity"
echo "      - Engine Version"
echo "      - Architecture"
echo "   5. In 'Connection Information' section, find:"
echo "      - Password (click 'Show' if enabled)"
echo "      - SSL Enabled"
echo ""
echo "Step 4: For Memcached (dcs-ibu2):"
echo "   1. Click 'Memcached' tab"
echo "   2. Find instance 'dcs-ibu2'"
echo "   3. Click on instance name"
echo "   4. In 'Basic Information' section, find:"
echo "      - Private IP"
echo "      - Specification"
echo "      - Capacity"
echo "      - Architecture"
echo "   5. In 'Connection Information' section, find:"
echo "      - Password (click 'Show' if enabled)"
echo ""
echo "📸 ALTERNATIVE: Take screenshots"
echo "----------------------------------------"
echo "If you can't copy all details, take screenshots of:"
echo "1. Redis instance details page"
echo "2. Memcached instance details page"
echo "3. Connection information for both"
echo ""
echo "🚀 ONCE YOU HAVE THIS INFORMATION:"
echo "================================================"
echo ""
echo "1. Run mig_worker deployment:"
echo "   ./quick_mig_worker_deploy.sh"
echo ""
echo "2. SSH to mig_worker:"
echo "   ssh -i ~/.ssh/mig-worker-key.pem ubuntu@[PRIVATE_IP]"
echo ""
echo "3. Test connectivity:"
echo "   redis-cli -h [REDIS_PRIVATE_IP] -p 6379 PING"
echo "   echo \"stats\" | nc [MEMCACHED_PRIVATE_IP] 11211"
echo ""
echo "4. Get detailed specs:"
echo "   redis-cli -h [REDIS_PRIVATE_IP] -p 6379 INFO"
echo "   echo \"stats\" | nc [MEMCACHED_PRIVATE_IP] 11211"
echo ""
echo "⚠️  URGENT: We need private IPs to proceed!"
echo "   Without private IPs, mig_worker cannot connect."
echo ""
echo "Please provide the private IPs first, then we continue."